import "./globals.css";
import AppHeader from "./partials/AppHeader";
export const metadata = {
  title: "Resume Builder v-2",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AppHeader />
        {children}
      </body>
    </html>
  );
}
