import "./globals.css";
import AppHeader from "./partials/AppHeader";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    
      <AppHeader />
      <body>{children}</body>
    </html>
  );
}
